#!/bin/bash
clear
echo -e "\033[1;33mOpciones:\033[1;30m
1) Eliminar usuario
2) Eliminar y desconectar todos del usuario
3) Desconectar todos del usuario\033[0m"
read -p ": " option
 if [ $option -eq 1 ]; then
 read -p "Nombre del usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario no existe"
 exit
 fi
 userdel --force $name > /dev/null 2>/dev/null
 echo "Usuario $name fue eliminado"
 exit
 fi

 if [ $option -eq 2 ]; then
 read -p "Nombre del usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario no existe"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 userdel $name 1>/dev/null 2>/dev/null
 echo "Usuario $name sera eliminado"
 exit
 fi

 if [ $option -eq 3 ]; then
 read -p "Nombre del usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario no existe"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 echo "Usuario $name fue eliminado"
 exit
 fi
