#!/bin/bash
#
# Dropbear & OpenSSH
# ========================
#

data=( `ps aux | grep -i dropbear | awk '{print $2}'`);
echo "=============================================="
echo "Usuarios [Dropbear]";
echo "[x]";

for PID in "${data[@]}"
do
        #echo "check $PID";
        NUM1=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | wc -l`;
        USER=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk '{print $10}'`;
        IP=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk '{print $12}'`;
        if [ $NUM1 -eq 1 ]; then
                echo "[PID] $PID - [Usuario]: $USER";
                echo "[TOTAL en Dropbear]: $NUM1";
        fi
done
echo "---";

data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);



echo "Usuarios [OpenSSH]";
echo "[x]";
for PID in "${data[@]}"
do
        #echo "check $PID";
        NUM2=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | wc -l`;
        USER=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | awk '{print $9}'`;
        IP=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | awk '{print $11}'`;
        if [ $NUM2 -eq 1 ]; then
                echo "[PID] $PID - [Usuario]: $USER";
                echo "[TOTAL en OpenSSH]: $NUM2";
        fi
done



echo "=============================================="
echo "VPSPack @PowerMX";
echo "=============================================="
