#!/bin/bash
cd
if [ $(id -u) != 0 ]
then
echo "Ejecute el script como root"
exit
fi
echo -e "\033[1;30mInstalando Script\033[0m"
mkdir /etc/VpsPackdir 2>/dev/null
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null
rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/powermx/vpspack/master/limite > /bin/limite
chmod +x /bin/limite
rm -rf /bin/criarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/powermx/vpspack/master/criarusuario > /bin/criarusuario
chmod +x /bin/criarusuario
rm -rf /bin/deletarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/powermx/vpspack/master/deletarusuario > /bin/deletarusuario
chmod +x /bin/deletarusuario
rm -rf /bin/redefinirusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/powermx/vpspack/master/redefinirusuario > /bin/redefinirusuario
chmod +x /bin/redefinirusuario
rm -rf /bin/vpspack 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/powermx/vpspack/master/vpspack > /bin/vpspack
chmod +x /bin/vpspack
rm -rf /bin/speedtest.py 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/powermx/vpspack/master/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py
wget -o /dev/null -O- https://raw.githubusercontent.com/powermx/vpspack/master/toolmaster > /bin/toolmaster
chmod +x /bin/toolmaster
wget -o /dev/null -O- https://raw.githubusercontent.com/powermx/vpspack/master/dropbear > /root/dropbear
chmod +x /root/dropbear
alias @actualizar='wget https://raw.githubusercontent.com/powermx/vpspack/master/install && bash install'
clear
echo -e "\033[1;32mInstalacion Finalizada\n\033[1;30mEjecute:"
echo -e "\n\033[1;32mvpspack \033[1;30mMenu de opciones"
echo -e "\033[1;32mOpcion 3 \033[1;30mCrear un usuario con fecha y limite"
echo -e "\033[1;32mOpcion 12 \033[1;30mBorrar un usuario o desconectarlo"
echo -e "\033[1;32mOpcion 11 \033[1;30mCambiar contraseña fecha o limite"
echo -e "\033[1;32mdropbear  \033[1;30mUsuarios conectados en Dropbear\033[0m"
echo -e "\033[1;32m@- \033[1;30mGrupo de Telegram : @PwrMX\033[0m"
echo -e "\033[1;32mVpsPack \033[1;30mInformacion en General\033[0m"
echo -e "\033[1;32mInstalada \033[1;30mVersion - 2.3\033[0m"
rm -rf install
